name: ai-shorts
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11.9
  - pip
  - numpy==1.26.4
  - pytorch==2.5.1
  - torchvision==0.20.1
  - pytorch-cuda=12.4
  - scipy==1.16.1
  - flask==3.1.2
  - psutil>=7.0.0,<8.0.0
  - pyyaml==6.0.2
  - tqdm==4.67.1
  - boto3>=1.40.20,<2.0.0
  - funcy>=2.0,<3.0
  - librosa==0.11.0
  - einops>=0.8.1,<0.9.0
  - timm==1.0.19
  - sentencepiece
  - imageio==2.37.0
  - av
  - libsndfile
  - pip:
      - basicsr==1.4.2
      - cog==0.16.6
      - dlib==20.0.0
      - dominate==2.9.1
      - easydict==1.13
      - face_alignment==1.4.1
      - facexlib==0.3.0
      - gradio==5.44.1
      - huggingface-hub==0.34.4
      - insightface==0.2.1
      - iou==0.1.0
      - kornia==0.8.1
      - launch==0.1.3
      - lws==1.2.8
      - matplotlib==3.10.6
      - menpo==0.11.1
      - moviepy==2.2.1
      - mxnet==1.9.1
      - onnx==1.19.0
      - onnxruntime==1.22.1
      - onnxsim==0.4.36
      - opencv-python==4.9.0.80
      - pandas==2.3.2
      - pillow==11.3.0
      - prettytable==3.16.0
      - pydub==0.25.1
      - python-speech-features==0.6
      - pytorch3d==0.7.4
      - realesrgan==0.3.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - sets==0.3.2
      - scikit-image==0.25.2
      - soundfile==0.13.1
      - tensorflow==2.20.0
      - transformers>=4.56.0,<5.0.0
      - tokenizers>=0.22.0,<0.23.0
      - trimesh==4.8.1
      - TTS==0.22.0
      - webui==0.1.7
      - yacs==0.1.8
      - piper-tts==1.3.0
      - imageio[ffmpeg]
